ROX-11335: Move Scanner DB secret out of main Scanner DB container
stackrox/scanner pull request #774
Opened 2022-06-09 22:34 UTC by RTann

This PR makes a few PostgreSQL-related updates:

* Move Scanner DB's secret out of the main Scanner DB container
    * This moves the secret into the init container, as it is only needed there
* Remove postgres-alpine image from CI
    * This is not needed, as we have PostgreSQL 12 in our CircleCI image
* Some Dockerfile cleanup

2022-06-09 23:10 UTC, RTann commented on .circleci/config.yml
> +          POSTGRES_PASSWORD: password
Took this from the stackrox repo, but we should probably not expose this nor make it obvious as maybe it's possible for someone who has access to the CI container to mess with the data. Any thoughts @gavin-stackrox ?

2022-06-09 23:11 UTC, RTann commented on .circleci/config.yml
> +          POSTGRES_PASSWORD: password
Note: we don't actually use this password for our needs. It was just required to set this environment variable in the latest postgres 12 version

2022-06-10 19:28 UTC, RTann commented
Removing reviewers for now, as it is not as ready as i originally thought

2022-06-16 15:30 UTC, connorgorman approved these changes
I would prefer we unify the Central and Scanner scripts and YAMLs. Does the way that Central-db do initialization work for scanner db?

2022-06-16 15:30 UTC, connorgorman requested changes
sorry meant to request changes and not approve

2022-06-16 18:13 UTC, RTann commented
> I would prefer we unify the Central and Scanner scripts and YAMLs. Does the way that Central-db do initialization work for scanner db?

Central does not initialize the database with data like Scanner does/needs: https://github.com/stackrox/stackrox/blob/3.70.0/image/templates/helm/stackrox-central/templates/01-central-12-central-db.yaml#L43. Central solely calls `docker-entrypoint.sh initdb ...` which just does `initdb` https://github.com/stackrox/stackrox/blob/3.70.0/image/postgres/scripts/docker-entrypoint.sh#L341. This just initializes the directory. We need to ensure the initial data is populated https://github.com/stackrox/scanner/blob/master/image/db/rhel/scripts/docker-entrypoint.sh#L336

2022-06-24 00:28 UTC, connorgorman approved these changes

2022-06-24 00:29 UTC, merged